version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "5.0.x"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: [ ">=4.0.0" ]
      - dependency-name: "javax.websocket:javax.websocket-client-api"
        versions: [ ">=1.1" ]
      - dependency-name: "javax.websocket:javax.websocket-api"
        versions: [ ">=1.1" ]
      - dependency-name: "com.google.javascript:closure-compiler"
        versions: [ ">=v20220502" ]
      - dependency-name: "org.graalvm.js:js"
        versions: [ ">=21.3.2.1" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=6.0.0" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ ">=3.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "2.0.x"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=11.0.0" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=6.0.0" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
