version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "3.0.x"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=12.0.0" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=6.0.0" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
